# Generated by Django 2.0.7 on 2018-07-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmpw',
        ),
    ]
