# Generated by Django 2.0.7 on 2018-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', to='gold.User'),
        ),
    ]
