# Generated by Django 2.0.7 on 2018-07-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20180724_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeornot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userslike', to='firstApp.User'),
        ),
    ]
